# ONJECT ORIENTED PROGRAMMING

# COMMON TOPIC IN ALMOST ALL POPULAR PROGRAMMING LANGUAGES(PYTHON , C++ , JAVA)
# WITH COMMON IDEA BUT WITH DIFFERENT SYNTAX

# OOPS IS JUST A STYLE/WAY TO WRITE A CODE

# VERY HELPFUL IN CREATING REAL WORLD PROGRAMS

# WE WILL SEE OTHER ADVANTAGES WHEN WE WILL START LEARNING OOP

# class , object(instance) , method 

# every thing in python is class